name: Terraform GCP Deployment

on:
  workflow_dispatch:
   inputs:
      environment:
        description: "Select the environment to deploy"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

jobs:
  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: envs/${{ github.event.inputs.environment }}

    permissions:
      contents: read

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Verify Authentication
        run: |
          gcloud auth list
          gcloud config list

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
